name: chupa
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip
  - pip:
    - pytorch-lightning==1.7.6
    - packaging==21.3
    - protobuf==3.20.*
    - torchmetrics==0.11.4
    - numpy==1.23.1
    - chumpy
    - gradio
    - pycocotools
    - torchgeometry
    - torchdiffeq
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - meshzoo
    - pymeshlab
    - pillow
    - scikit-image
    - tensorboard
    - tqdm
    - trimesh
    - albumentations
    - pudb 
    - omegaconf
    - test-tube
    - streamlit
    - einops
    - torch-fidelity
    - transformers
    - xformers
    - PyOpenGL
    - pygifsicle
    - jsonmerge
    - scipy
    - resize_right
    - clip
    - clean-fid
    - kornia
    - smplx
    - setuptools
    - git+https://github.com/YuliangXiu/rembg.git
    - git+https://github.com/NVlabs/nvdiffrast.git
    - -e .